name: flutter_kickstart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  go_router: ^7.1.1
  hooks_riverpod: ^2.3.6
  intl: ^0.18.0
  material_color_utilities: ^0.2.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # flutter pub run build_runner watch --delete-conflicting-outputs
  # (you're welcome)
  build_runner:
  riverpod_generator:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true
  generate: true
