name: flutter_kickstart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.8
  hooks_riverpod: ^2.2.0 
  intl: ^0.17.0
  material_color_utilities: ^0.1.5
  riverpod_annotation: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # flutter pub run build_runner watch --delete-conflicting-outputs
  # (you're welcome)
  build_runner:
  riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
