name: flutter_kickstart
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^0.0.1
  hooks_riverpod: ^2.2.0 
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  material_color_utilities: ^0.1.5
  riverpod_annotation: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner:
  isar_generator: ^3.0.5
  riverpod_generator: ^1.1.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  generate: true
